import { cleanup, render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";

import { DraftSegmenter } from "~/.server/draft-segmenter";
import { FixtureTutorApi } from "~/.server/fixture-tutor-api";
import { TurnProjection } from "~/.server/turn-projection";
import { ChainBreakNotice } from "~/components/turn/chain-break-notice";
import { ContextPanel } from "~/components/turn/context-panel";
import { DraftPanel } from "~/components/turn/draft-panel";
import { GateTimeline } from "~/components/turn/gate-timeline";
import { PromptPanel } from "~/components/turn/prompt-panel";
import { SafetyFlagPanel } from "~/components/turn/safety-flag-panel";

afterEach(() => {
  cleanup();
});

const projection = new TurnProjection(new DraftSegmenter());
const api = new FixtureTutorApi();
const { completed, halted, refused } = FixtureTutorApi.turnIds;

async function turn(turnId: string) {
  const detail = await api.turn(turnId);
  return projection.project(detail.record, detail.cited);
}

describe("GateTimeline", () => {
  it("shows every gate state in words, including ones not reached", async () => {
    const { gates, policyVersion } = await turn(halted);
    render(<GateTimeline gates={gates} policyVersion={policyVersion} />);
    expect(screen.getByText("Checked and passed")).toBeTruthy();
    expect(screen.getByText("Checked and fired (stop)")).toBeTruthy();
    expect(screen.getAllByText("Not reached")).toHaveLength(2);
    expect(
      screen.getByText("The retrieved notes disagree about ser and estar."),
    ).toBeTruthy();
    expect(screen.getByText("Policy version policy-1")).toBeTruthy();
  });
});

describe("DraftPanel", () => {
  it("marks an unsupported span in place and cites the supported one", async () => {
    const { draft } = await turn(completed);
    render(<DraftPanel draft={draft} />);
    const marked = screen.getByText("It is also used for temporary states.");
    expect(marked.tagName).toBe("MARK");
    expect(screen.getByText("Unsupported")).toBeTruthy();
    expect(screen.getByText("Source").parentElement?.textContent).toBe(
      "Source 1",
    );
    expect(screen.getByText(/generated by the tutoring system/)).toBeTruthy();
    expect(screen.getByText("Output before checks")).toBeTruthy();
  });

  it("renders a refusal without an output before checks", async () => {
    const { draft } = await turn(refused);
    render(<DraftPanel draft={draft} />);
    expect(
      screen.getByText("This question is outside the lesson."),
    ).toBeTruthy();
    expect(
      screen.getByText(
        "The model was not called, so there is no output before checks.",
      ),
    ).toBeTruthy();
  });

  it("says the draft was not reached when generation did not run", () => {
    render(<DraftPanel draft={null} />);
    const region = screen.getByRole("region", { name: "Generated draft" });
    expect(within(region).getByText("Not reached.")).toBeTruthy();
  });

  it("omits the disclosure line when no disclosure was recorded", async () => {
    const { draft } = await turn(completed);
    if (!draft) {
      throw new Error("completed fixture has a draft");
    }
    render(<DraftPanel draft={{ ...draft, disclosure: null }} />);
    expect(screen.queryByText(/Disclosure:/)).toBeNull();
  });
});

describe("SafetyFlagPanel", () => {
  it("distinguishes no flags from checks that did not run", () => {
    const { rerender } = render(
      <SafetyFlagPanel flags={[]} support={{ ratio: 1 }} />,
    );
    expect(screen.getByText("No safety flags.")).toBeTruthy();
    expect(screen.getByText("Support ratio 1.00")).toBeTruthy();

    rerender(<SafetyFlagPanel flags={null} support={null} />);
    expect(screen.getByText("Checks did not run.")).toBeTruthy();
    expect(screen.getByText("Source support was not checked.")).toBeTruthy();
  });

  it("shows each flag with its severity", async () => {
    const { flags, support } = await turn(refused);
    render(<SafetyFlagPanel flags={flags} support={support} />);
    expect(screen.getByText("Severity high")).toBeTruthy();
    expect(
      screen.getByText("The prompt asks for a home address."),
    ).toBeTruthy();
  });
});

describe("ContextPanel", () => {
  it("distinguishes retrieval not reached from nothing retrieved", () => {
    const { rerender } = render(<ContextPanel context={null} />);
    expect(screen.getByText("Not reached.")).toBeTruthy();
    rerender(<ContextPanel context={[]} />);
    expect(screen.getByText("No snippets were retrieved.")).toBeTruthy();
  });

  it("numbers each snippet the way the draft cites it", async () => {
    const { context } = await turn(completed);
    render(<ContextPanel context={context} />);
    expect(screen.getByText("Source 1")).toBeTruthy();
    expect(screen.getByText("kb://grammar/ser")).toBeTruthy();
    expect(screen.getByText("Review status reviewed")).toBeTruthy();
  });
});

describe("PromptPanel", () => {
  it("lists the redacted categories", async () => {
    const { prompt } = await turn(refused);
    render(<PromptPanel prompt={prompt} />);
    expect(screen.getByText("What is my [address]?")).toBeTruthy();
    expect(screen.getByText("address")).toBeTruthy();
  });

  it("says so when nothing was redacted", async () => {
    const { prompt } = await turn(completed);
    render(<PromptPanel prompt={prompt} />);
    expect(screen.getByText("No redacted categories.")).toBeTruthy();
  });
});

describe("ChainBreakNotice", () => {
  it.each([
    ["tampered", "no longer matches its digest"],
    ["excised", "is missing from the chain"],
    ["unreadable", "could not be read"],
  ] as const)("explains a %s record", (reason, explanation) => {
    render(<ChainBreakNotice chainBreak={{ turnId: completed, reason }} />);
    const alert = screen.getByRole("alert");
    expect(alert.textContent).toContain(completed);
    expect(alert.textContent).toContain(explanation);
  });
});
