"""Retrieval and generation agents, and the two edges the gates guard."""

import inspect

import pytest
from pydantic import ValidationError
from tests.support.samples import Samples
from tests.support.turn_stubs import (
    Agents,
    CountingHistory,
    CountingKnowledge,
    EmptyKnowledge,
    FindingGrammar,
    FixedTemplate,
    FlaggingSafety,
    RecordingModel,
    ReportingSupport,
    ScriptedGate,
)

from tutor_api.adapters.checks.safety import CategorySafetyClassifier, MinorSafetyRules
from tutor_core.application.agents.generation import ContentGenerationAgent
from tutor_core.application.agents.retrieval import DataRetrievalAgent
from tutor_core.application.turn.guarded_generation import GenerateIfConsistent
from tutor_core.application.turn.guarded_retrieval import RetrieveIfPermitted
from tutor_core.domain.models.learner import HistoryFieldSet
from tutor_core.domain.models.pipeline import (
    GeneratedDraft,
    GuardedGenerationResult,
    GuardedRetrievalResult,
)
from tutor_core.domain.models.retrieval import RetrievedContext
from tutor_core.domain.models.safety import SafetyFlag
from tutor_core.domain.ports.safety_classifier import SafetyClassifierPort

_REQUESTED = HistoryFieldSet(fields=("proficiency_level",))


class TestDataRetrievalAgent:
    async def test_empty_retrieval_is_a_result(self) -> None:
        history = CountingHistory()
        agent = DataRetrievalAgent(EmptyKnowledge(), history)
        context = await agent.retrieve(
            Samples().redacted_request(), Samples().learner_id(), _REQUESTED
        )
        assert context.knowledge.snippets == ()
        assert context.knowledge.confidence == 0.0
        assert context.history.proficiency_level == "A1"
        assert history.calls == 1
        assert history.requested == [_REQUESTED]

    async def test_every_snippet_keeps_its_source(self) -> None:
        agent = DataRetrievalAgent(CountingKnowledge(), CountingHistory())
        context = await agent.retrieve(
            Samples().redacted_request(), Samples().learner_id(), _REQUESTED
        )
        assert context.knowledge.snippets[0].source == Samples().source()

    def test_the_agent_holds_only_knowledge_and_history(self) -> None:
        names = set(inspect.signature(DataRetrievalAgent).parameters)
        assert names == {"knowledge", "history"}


class TestContentGenerationAgent:
    def _agent(
        self,
        safety: SafetyClassifierPort,
        model: RecordingModel | None = None,
    ) -> tuple[ContentGenerationAgent, RecordingModel]:
        language = model if model is not None else RecordingModel()
        return Agents().generation(safety, language), language

    async def test_disclosure_is_on_the_output_and_the_draft_is_not_edited(
        self,
    ) -> None:
        high = Samples().safety_flag().model_copy(update={"severity": "high"})
        agent, language = self._agent(FlaggingSafety((high,)))
        draft = await agent.generate(
            "Where is the library?",
            Samples().retrieval(),
            Samples().history(),
        )
        assert language.calls == 1
        assert draft.unit.ai_disclosure == "This reply was generated by an AI tutor."
        assert draft.unit.output_before_checks == draft.unit.output_after_checks
        assert draft.unit.refused is False
        assert draft.unit.grammar == (Samples().grammar(),)
        assert draft.unit.support.unsupported
        assert draft.template_version == "tpl-1"
        assert draft.model_revision == "a" * 64
        assert draft.decoding_params == Samples().decoding()
        assert draft.model_ran() is True

    async def test_a_high_severity_task_refuses_without_calling_the_model(self) -> None:
        high = (
            Samples()
            .safety_flag()
            .model_copy(
                update={"severity": "high", "message": "This asks for the open web."}
            )
        )
        agent, language = self._agent(FlaggingSafety((high,)))
        draft = await agent.generate(
            "search the web",
            Samples().retrieval(),
            Samples().history(),
        )
        assert language.calls == 0
        assert draft.unit.refused is True
        assert draft.unit.refusal_reason == "This asks for the open web."
        # No model output was produced, so none is recorded as if it had been.
        assert draft.unit.output_before_checks is None
        assert draft.unit.output_after_checks == "This asks for the open web."
        assert draft.unit.ai_disclosure
        assert draft.model_ran() is False
        assert draft.decoding_params is None
        assert draft.model_revision is None
        assert draft.template_version is None

    async def test_mixed_case_medical_advice_refuses_before_the_model(self) -> None:
        agent, language = self._agent(
            CategorySafetyClassifier(MinorSafetyRules().rules())
        )
        draft = await agent.generate(
            "Please Diagnose this",
            Samples().retrieval(),
            Samples().history(),
        )
        assert language.calls == 0
        assert draft.unit.refused is True
        assert draft.unit.output_before_checks is None
        assert "medical advice" in (draft.unit.refusal_reason or "")

    async def test_a_high_severity_draft_refuses_and_keeps_the_draft(self) -> None:
        class DraftSafety(SafetyClassifierPort):
            def classify(self, text: str) -> tuple[SafetyFlag, ...]:
                if text == "Hola means hello.":
                    return (
                        Samples()
                        .safety_flag()
                        .model_copy(
                            update={"severity": "high", "message": "Unsafe draft."}
                        ),
                    )
                return ()

        agent, language = self._agent(DraftSafety())
        draft = await agent.generate(
            "hello", Samples().retrieval(), Samples().history()
        )
        assert language.calls == 1
        assert draft.unit.refused is True
        assert draft.unit.output_before_checks == "Hola means hello."
        assert draft.unit.output_after_checks == "Hola means hello."

    def test_an_empty_disclosure_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="disclosure"):
            ContentGenerationAgent(
                FixedTemplate(),
                RecordingModel(),
                FindingGrammar(),
                FlaggingSafety((Samples().safety_flag(),)),
                ReportingSupport(),
                "   ",
            )

    def test_the_agent_holds_no_retriever(self) -> None:
        names = set(inspect.signature(ContentGenerationAgent).parameters)
        assert "knowledge" not in names
        assert "history" not in names
        assert names == {
            "template",
            "model",
            "grammar",
            "safety",
            "support",
            "disclosure",
        }


class TestGuardedRetrieval:
    async def test_permission_stop_means_retrieval_is_never_called(self) -> None:
        knowledge = CountingKnowledge()
        history = CountingHistory()
        guard = RetrieveIfPermitted(
            ScriptedGate("stop", "context_and_permission"),
            DataRetrievalAgent(knowledge, history),
        )
        result = await guard.run(Samples().turn())
        assert result.verdict.decision == "stop"
        assert result.context is None
        assert knowledge.calls == 0
        assert history.calls == 0

    async def test_a_pass_retrieves_exactly_the_requested_history(self) -> None:
        knowledge = CountingKnowledge()
        history = CountingHistory()
        guard = RetrieveIfPermitted(
            ScriptedGate("pass", "context_and_permission"),
            DataRetrievalAgent(knowledge, history),
        )
        turn = Samples().turn()
        turn.requested_history_fields = ("events",)
        result = await guard.run(turn)
        assert result.context is not None
        assert knowledge.calls == 1
        assert history.requested == [HistoryFieldSet(fields=("events",))]

    async def test_a_pass_without_a_prompt_raises(self) -> None:
        guard = RetrieveIfPermitted(
            ScriptedGate("pass", "context_and_permission"),
            DataRetrievalAgent(CountingKnowledge(), CountingHistory()),
        )
        turn = Samples().turn()
        turn.learner_prompt = None
        with pytest.raises(ValueError, match="no prompt"):
            await guard.run(turn)


class TestGuardedGeneration:
    async def test_conflict_pause_means_the_model_is_never_invoked(self) -> None:
        language = RecordingModel()
        guard = GenerateIfConsistent(
            ScriptedGate("pause", "conflict_and_ambiguity"),
            Agents().generation(model=language),
        )
        result = await guard.run(Samples().turn())
        assert result.verdict.decision == "pause"
        assert result.draft is None
        assert language.calls == 0

    async def test_a_pass_without_retrieval_raises(self) -> None:
        guard = GenerateIfConsistent(
            ScriptedGate("pass", "conflict_and_ambiguity"), Agents().generation()
        )
        turn = Samples().turn()
        turn.retrieved = None
        with pytest.raises(ValueError, match="no prompt, retrieval or history"):
            await guard.run(turn)

    async def test_a_pass_generates_from_the_redacted_prompt(self) -> None:
        language = RecordingModel()
        safety = FlaggingSafety()
        guard = GenerateIfConsistent(
            ScriptedGate("pass", "conflict_and_ambiguity"),
            Agents().generation(safety, language),
        )
        turn = Samples().turn()
        result = await guard.run(turn)
        assert result.draft is not None
        assert language.calls == 1
        assert turn.learner_prompt is not None
        assert safety.texts[0] == turn.learner_prompt.text


class TestGuardedResults:
    def test_a_pass_without_a_product_is_rejected(self) -> None:
        passed = Samples().verdict()
        with pytest.raises(ValidationError, match="no retrieved context"):
            GuardedRetrievalResult(verdict=passed, context=None)
        with pytest.raises(ValidationError, match="no draft"):
            GuardedGenerationResult(verdict=passed, draft=None)

    def test_a_halt_with_a_product_is_rejected(self) -> None:
        stopped = Samples().verdict().model_copy(update={"decision": "stop"})
        context = RetrievedContext(
            knowledge=Samples().retrieval(),
            history=Samples().history(),
        )
        with pytest.raises(ValidationError, match="retrieval ran"):
            GuardedRetrievalResult(verdict=stopped, context=context)
        draft = GeneratedDraft(
            unit=Samples().generated(),
            safety_flags=(),
            template_version="tpl-1",
            model_revision="a" * 64,
            decoding_params=Samples().decoding(),
        )
        with pytest.raises(ValidationError, match="generation ran"):
            GuardedGenerationResult(verdict=stopped, draft=draft)


class TestGeneratedDraft:
    def test_a_model_output_without_its_pins_is_rejected(self) -> None:
        with pytest.raises(ValidationError, match="needs its template"):
            GeneratedDraft(unit=Samples().generated(), safety_flags=())

    def test_a_draft_the_model_did_not_write_carries_no_pins(self) -> None:
        refusal = (
            Samples()
            .generated()
            .model_copy(
                update={
                    "output_before_checks": None,
                    "refused": True,
                    "refusal_reason": "no",
                }
            )
        )
        with pytest.raises(ValidationError, match="carries no model pins"):
            GeneratedDraft(unit=refusal, safety_flags=(), model_revision="a" * 64)

    def test_only_a_refusal_may_lack_model_output(self) -> None:
        with pytest.raises(ValidationError, match="only a refusal"):
            Samples().generated().model_validate(
                {**Samples().generated().model_dump(), "output_before_checks": None}
            )
