"""What this prototype deployment binds: wording, rule ids, and its policy card.

The container hands these to the gates and agents as constructor arguments.
The operator seed publishes ``PrototypePolicyCard`` so that every rule a gate
can cite is on the card in force; a verdict still resolves its rule on that
card, so a card without the rule fails closed (REQ-POLICY).
"""

from tutor_core.domain.models.gate_rules import (
    ConflictRuleIds,
    DriftEnvelope,
    DriftRuleIds,
    PermissionRuleIds,
    SensitivityRuleIds,
)
from tutor_core.domain.models.safety import DecodingParams
from tutor_core.domain.policy.policy_card import ArticleMapping, PolicyCard, PolicyRule


class PrototypeCopy:
    """Wording, rule identifiers and limits this deployment binds."""

    def permission_rules(self) -> PermissionRuleIds:
        """Article 14 permission rules, plus the Article 10 history minimum."""
        return PermissionRuleIds(
            in_scope="permission-in-scope",
            unvetted_source="permission-unvetted-source",
            history_outside_minimum="permission-history-minimum",
            indeterminate="permission-indeterminate",
            evaluation_failed="permission-evaluation-failed",
        )

    def conflict_rules(self) -> ConflictRuleIds:
        """Article 14 conflict rules. ``threshold`` states the float."""
        return ConflictRuleIds(
            sufficient="conflict-sufficient",
            empty="conflict-empty",
            low_confidence="conflict-low-confidence",
            contradiction="conflict-contradiction",
            evaluation_failed="conflict-evaluation-failed",
            threshold="conflict-threshold",
        )

    def sensitivity_rules(self) -> SensitivityRuleIds:
        """Article 14 sensitivity rules."""
        return SensitivityRuleIds(
            routine="sensitivity-routine",
            flagged_category="sensitivity-flagged-category",
            refused="sensitivity-refused",
            evaluation_failed="sensitivity-evaluation-failed",
        )

    def drift_rules(self) -> DriftRuleIds:
        """Article 14 and 15 drift rules."""
        return DriftRuleIds(
            within_envelope="drift-within-envelope",
            outside_envelope="drift-outside-envelope",
            evaluation_failed="drift-evaluation-failed",
        )

    def drift_envelope(self) -> DriftEnvelope:
        """The per-turn envelope (ARCHITECTURE §13 scopes drift per session)."""
        return DriftEnvelope(
            min_retrieval_confidence=0.3,
            min_support_ratio=0.5,
            max_output_characters=1200,
            max_grammar_findings=3,
        )

    def flagged_categories(self) -> tuple[str, ...]:
        """Safety categories the sensitivity gate holds for the tutor."""
        return ("proficiency", "unsafe", "out_of_scope")

    def unvetted_source_categories(self) -> tuple[str, ...]:
        """Safety categories meaning a question needs the open web."""
        return ("out_of_scope",)

    def disclosure(self) -> str:
        """The sentence on every output, including a refusal (REQ-MINOR)."""
        return "This reply was generated by an AI tutor."

    def template_version(self) -> str:
        """Logged with the turn (REQ-ACCURACY)."""
        return "tpl-1"

    def role(self) -> str:
        """The fixed role section."""
        return "You are a language tutor helping a minor learner."

    def structure(self) -> str:
        """The fixed output-structure section."""
        return "Answer in one short paragraph a tutor can check."

    def tone(self) -> str:
        """The fixed tone constraint (REQ-MINOR)."""
        return "Use simple words a child can read. Be kind and brief."

    def decoding(self) -> DecodingParams:
        """Recorded on every completion that calls the model."""
        return DecodingParams(temperature=0.0, top_p=1.0, max_tokens=256)


class PrototypePolicyCard:
    """The card naming every rule the four gates can cite.

    ``threshold`` is the conflict rule's statement. It must equal
    ``CONFLICT_CONFIDENCE_THRESHOLD``; the conflict gate checks the two on
    every evaluation and stops the turn when they differ.
    """

    def __init__(self, copy: PrototypeCopy) -> None:
        self._copy = copy

    def build(self, version: str, threshold: str) -> PolicyCard:
        """Return the card for ``version``."""
        permission = self._copy.permission_rules()
        conflict = self._copy.conflict_rules()
        sensitivity = self._copy.sensitivity_rules()
        drift = self._copy.drift_rules()
        return PolicyCard(
            version=version,
            allowed_actions=(
                self._rule(permission.in_scope, "The question is in scope.", "14"),
                self._rule(conflict.sufficient, "The material is sufficient.", "14"),
                self._rule(sensitivity.routine, "Routine content continues.", "14"),
                self._rule(
                    drift.within_envelope, "In-envelope output continues.", "15"
                ),
            ),
            denied_actions=(
                self._rule(
                    permission.unvetted_source, "Unvetted sources are denied.", "14"
                ),
                self._rule(
                    permission.history_outside_minimum,
                    "History outside the minimum is denied.",
                    "10",
                ),
                self._rule(permission.evaluation_failed, "A failed check stops.", "14"),
                self._rule(conflict.evaluation_failed, "A failed check stops.", "14"),
                self._rule(sensitivity.refused, "A refusal stops for review.", "14"),
                self._rule(
                    sensitivity.evaluation_failed, "A failed check stops.", "14"
                ),
                self._rule(drift.evaluation_failed, "A failed check stops.", "14"),
            ),
            escalation_rules=(
                self._rule(
                    permission.indeterminate, "Indeterminate scope pauses.", "14"
                ),
                self._rule(conflict.empty, "Empty retrieval pauses.", "14"),
                self._rule(conflict.low_confidence, "Low confidence pauses.", "14"),
                self._rule(conflict.contradiction, "A contradiction pauses.", "14"),
                self._rule(conflict.threshold, threshold, "14"),
                self._rule(
                    sensitivity.flagged_category, "A flagged category pauses.", "14"
                ),
                self._rule(
                    drift.outside_envelope, "Output outside the envelope pauses.", "15"
                ),
            ),
            article_mappings=(
                ArticleMapping(article="14", locus="oversight gates"),
                ArticleMapping(article="10", locus="history minimum"),
                ArticleMapping(article="15", locus="drift envelope"),
            ),
        )

    def _rule(self, rule_id: str, statement: str, article: str) -> PolicyRule:
        return PolicyRule(
            policy_rule_id=rule_id,
            statement=statement,
            article=article,
        )
