"""A full turn over HTTP: router → ConductTurn → LangGraph → gates → Postgres.

Real container, real database, real gates, real policy card from the operator
seed. Only the language model is stubbed, and only for determinism (rule 7).
Gate placement is asserted on the database: what ran, what never ran, and the
four gate rows the turn committed with.
"""

from collections.abc import Iterator
from datetime import UTC, datetime
from uuid import UUID

import psycopg
import pytest
from fastapi.testclient import TestClient
from tests.support.turn_app import TurnApp
from tests.support.turn_stubs import RecordingModel

from tutor_api.adapters.persistence.database import DatabaseEngine
from tutor_api.curation.prototype_seed import SeedPlan
from tutor_api.di.container import Container
from tutor_api.main import Application
from tutor_core.domain.models.safety import ModelCompletion, RenderedPrompt
from tutor_core.domain.ports.cipher import CipherPort


class FailingModel(RecordingModel):
    """The runtime goes away mid-turn."""

    async def complete(self, prompt: RenderedPrompt) -> ModelCompletion:
        self.calls += 1
        msg = "ollama is not reachable"
        raise ValueError(msg)


class StoppingModel(RecordingModel):
    """The tutor stops the session while the model is generating."""

    def __init__(self, url: str) -> None:
        super().__init__("Hola means hello in Spanish.")
        self._url = url
        self.session_id: UUID | None = None

    async def complete(self, prompt: RenderedPrompt) -> ModelCompletion:
        assert self.session_id is not None
        with psycopg.connect(self._url) as connection:
            connection.execute(
                "UPDATE tutoring_session SET stopped_at = %s WHERE id = %s",
                (datetime(2026, 10, 6, tzinfo=UTC), self.session_id),
            )
        return await super().complete(prompt)


class Served:
    """One seeded database, the application over it, and the stubbed model."""

    def __init__(self, url: str, model: RecordingModel) -> None:
        self.url = url
        self.model = model
        self.app = TurnApp(url)
        self.container: Container = self.app.container(model)
        self.plan: SeedPlan | None = None

    async def install(self) -> None:
        self.plan = await self.app.install(self.container)

    def body(
        self, prompt: str, fields: tuple[str, ...] = ("proficiency_level",)
    ) -> dict[str, object]:
        assert self.plan is not None
        return {
            "session_id": str(self.plan.session_id),
            "learner_id": str(self.plan.learner_id),
            "prompt": prompt,
            "requested_history_fields": list(fields),
        }

    def client(self) -> Iterator[TestClient]:
        with TestClient(Application(self.container).asgi()) as client:
            yield client
            engine = self.container.resolve(DatabaseEngine)
            assert isinstance(engine, DatabaseEngine)
            client.portal.call(engine.dispose)  # type: ignore[union-attr]

    def rows(self, query: str, *values: object) -> list[tuple[object, ...]]:
        with psycopg.connect(self.url) as connection:
            return connection.execute(query, values).fetchall()

    def gates(self, turn_id: str) -> list[tuple[object, ...]]:
        return self.rows(
            """
            SELECT gate_name, decision, policy_rule_id
            FROM gate_evaluation WHERE turn_id = %s
            ORDER BY CASE gate_name
                WHEN 'context_and_permission' THEN 0
                WHEN 'conflict_and_ambiguity' THEN 1
                WHEN 'sensitivity_and_high_stakes' THEN 2
                ELSE 3 END
            """,
            UUID(turn_id),
        )


@pytest.fixture
async def served(fresh_database: str) -> Served:
    served = Served(fresh_database, RecordingModel("Hola means hello in Spanish."))
    await served.install()
    return served


class TestConductTurnOverHttp:
    async def test_a_turn_inside_scope_passes_all_four_gates_and_awaits_the_tutor(
        self, served: Served
    ) -> None:
        for client in served.client():
            response = client.post(
                "/turns", json=served.body("What does hola mean in Spanish?")
            )
        assert response.status_code == 200, response.text
        outcome = response.json()
        assert outcome["status"] == "awaiting_tutor_approval"
        assert outcome["halted_at"] is None
        assert outcome["reply"] == "Hola means hello in Spanish."
        assert outcome["ai_disclosure"] == "This reply was generated by an AI tutor."
        assert outcome["sources"] == ["kb://spanish/greetings"]
        assert outcome["policy_version"] == "prototype-1"
        assert served.model.calls == 1
        assert [row[1] for row in served.gates(outcome["turn_id"])] == ["pass"] * 4
        audit = served.rows(
            "SELECT turn_index, model_revision, record_hash FROM turn_audit"
        )
        assert audit == [(0, "a" * 64, outcome["record_hash"])]
        citations = served.rows("SELECT count(*) FROM turn_citation")
        assert citations[0][0] >= 1

    async def test_permission_stop_means_retrieval_and_the_model_never_run(
        self, served: Served
    ) -> None:
        for client in served.client():
            response = client.post(
                "/turns",
                json=served.body(
                    "What does hola mean?", ("proficiency_level", "pseudonym")
                ),
            )
        outcome = response.json()
        assert outcome["status"] == "held_for_review"
        assert outcome["halted_at"] == "context_and_permission"
        assert served.model.calls == 0
        assert [row[1] for row in served.gates(outcome["turn_id"])] == [
            "stop",
            "not_evaluated",
            "not_evaluated",
            "not_evaluated",
        ]
        assert {row[2] for row in served.gates(outcome["turn_id"])} == {
            "permission-history-minimum"
        }
        assert served.rows("SELECT count(*) FROM turn_citation") == [(0,)]
        assert served.rows("SELECT model_revision FROM turn_audit") == [(None,)]

    async def test_an_open_web_question_stops_at_permission(
        self, served: Served
    ) -> None:
        for client in served.client():
            response = client.post(
                "/turns", json=served.body("Can you search the web for hola?")
            )
        outcome = response.json()
        assert outcome["halted_at"] == "context_and_permission"
        assert served.gates(outcome["turn_id"])[0][2] == "permission-unvetted-source"
        assert served.model.calls == 0

    async def test_mixed_case_open_web_still_stops_at_permission(
        self, served: Served
    ) -> None:
        for client in served.client():
            response = client.post(
                "/turns", json=served.body("Search the Web for hola")
            )
        outcome = response.json()
        assert outcome["halted_at"] == "context_and_permission"
        assert served.gates(outcome["turn_id"])[0][2] == "permission-unvetted-source"
        assert served.model.calls == 0

    async def test_another_learners_session_is_rejected_before_retrieval(
        self, served: Served
    ) -> None:
        body = served.body("What does hola mean in Spanish?")
        body["learner_id"] = "20000000-0000-4000-8000-000000000099"
        for client in served.client():
            response = client.post("/turns", json=body)
        assert response.status_code == 422
        assert "different learner" in response.json()["detail"]
        assert served.model.calls == 0
        assert served.rows("SELECT count(*) FROM turn_audit") == [(0,)]

    async def test_a_stopped_session_is_rejected_before_retrieval(
        self, served: Served
    ) -> None:
        assert served.plan is not None
        with psycopg.connect(served.url) as connection:
            connection.execute(
                "UPDATE tutoring_session SET stopped_at = %s WHERE id = %s",
                (datetime(2026, 10, 6, tzinfo=UTC), served.plan.session_id),
            )
        for client in served.client():
            response = client.post(
                "/turns", json=served.body("What does hola mean in Spanish?")
            )
        assert response.status_code == 422
        assert response.json()["detail"] == "session is stopped"
        assert served.model.calls == 0
        assert served.rows("SELECT count(*) FROM turn_audit") == [(0,)]

    async def test_a_session_stopped_during_generation_keeps_no_audit_row(
        self, fresh_database: str
    ) -> None:
        model = StoppingModel(fresh_database)
        served = Served(fresh_database, model)
        await served.install()
        assert served.plan is not None
        model.session_id = served.plan.session_id
        for client in served.client():
            response = client.post(
                "/turns", json=served.body("What does hola mean in Spanish?")
            )
        assert model.calls == 1
        assert response.status_code == 422
        assert response.json()["detail"] == "session is stopped"
        assert served.rows("SELECT count(*) FROM turn_audit") == [(0,)]
        assert served.rows("SELECT count(*) FROM gate_evaluation") == [(0,)]

    async def test_an_unknown_session_is_rejected_before_retrieval(
        self, served: Served
    ) -> None:
        body = served.body("What does hola mean in Spanish?")
        body["session_id"] = "30000000-0000-4000-8000-000000000099"
        for client in served.client():
            response = client.post("/turns", json=body)
        assert response.status_code == 422
        assert response.json()["detail"] == "session is not known"
        assert served.model.calls == 0
        assert served.rows("SELECT count(*) FROM turn_audit") == [(0,)]

    async def test_conflict_pause_means_the_model_is_never_invoked(
        self, served: Served
    ) -> None:
        for client in served.client():
            response = client.post(
                "/turns", json=served.body("Tell me about volcanoes")
            )
        outcome = response.json()
        assert outcome["status"] == "held_for_review"
        assert outcome["halted_at"] == "conflict_and_ambiguity"
        assert served.model.calls == 0
        decisions = [row[1] for row in served.gates(outcome["turn_id"])]
        assert decisions == ["pass", "pause", "not_evaluated", "not_evaluated"]

    async def test_a_second_turn_continues_the_session_chain(
        self, served: Served
    ) -> None:
        for client in served.client():
            first = client.post(
                "/turns", json=served.body("What does hola mean in Spanish?")
            ).json()
            second = client.post(
                "/turns", json=served.body("Tell me about volcanoes")
            ).json()
        assert (first["turn_index"], second["turn_index"]) == (0, 1)
        link = served.rows(
            "SELECT previous_record_hash FROM turn_audit WHERE turn_index = 1"
        )
        assert link == [(first["record_hash"],)]

    async def test_a_failed_turn_returns_503_and_leaves_no_partial_record(
        self, fresh_database: str
    ) -> None:
        served = Served(fresh_database, FailingModel())
        await served.install()
        for client in served.client():
            response = client.post(
                "/turns", json=served.body("What does hola mean in Spanish?")
            )
        assert response.status_code == 503
        assert "nothing was kept" in response.json()["detail"]
        assert "hola" not in response.text.lower()
        assert served.model.calls == 1
        assert served.rows("SELECT count(*) FROM turn_audit") == [(0,)]
        assert served.rows("SELECT count(*) FROM gate_evaluation") == [(0,)]
        assert served.rows("SELECT count(*) FROM turn_citation") == [(0,)]

    async def test_a_raw_name_in_the_prompt_never_reaches_the_log(
        self, served: Served
    ) -> None:
        for client in served.client():
            client.post(
                "/turns",
                json=served.body("My name is Ada. What does hola mean in Spanish?"),
            )
        sealed = served.rows("SELECT learner_prompt_redacted FROM turn_audit")
        cipher = served.container.resolve(CipherPort)
        assert isinstance(cipher, CipherPort)
        stored = cipher.decrypt(bytes(sealed[0][0])).decode("utf-8")  # type: ignore[arg-type]
        assert "Ada" not in stored
        assert "hola" in stored
