import { TutorApi } from "~/.server/tutor-api";
import type {
  AuditJson,
  GateEvaluationJson,
  SessionSummaryJson,
  TurnDetailJson,
} from "~/.server/tutor-api.types";
import type { GateName } from "~/lib/gates";

type FixtureSession = {
  summary: SessionSummaryJson;
  turns: TurnDetailJson[];
};

const POLICY = "policy-1";
const DISCLOSURE =
  "This text was generated by the tutoring system for a tutor to review.";
const CHUNK = "dddddddd-dddd-4ddd-8ddd-dddddddddddd";

/**
 * The three turns FE-02 requires — completed, halted, and refused — shaped
 * exactly as FastAPI returns them, so fixture mode exercises the same
 * projection as live mode.
 */
export class FixtureTutorApi extends TutorApi {
  static readonly sessionIds = {
    completed: "11111111-1111-4111-8111-111111111111",
    halted: "22222222-2222-4222-8222-222222222222",
    refused: "33333333-3333-4333-8333-333333333333",
  } as const;

  static readonly turnIds = {
    completed: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    halted: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    refused: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
  } as const;

  async sessions(): Promise<SessionSummaryJson[]> {
    return this.catalogue().map((session) => session.summary);
  }

  async session(sessionId: string): Promise<SessionSummaryJson> {
    return this.find(sessionId).summary;
  }

  async audit(sessionId: string): Promise<AuditJson> {
    return {
      records: this.find(sessionId).turns.map((turn) => turn.record),
      intact: true,
      break_turn_id: null,
      break_reason: null,
    };
  }

  async turn(turnId: string): Promise<TurnDetailJson> {
    for (const session of this.catalogue()) {
      const turn = session.turns.find((item) => item.record.turn_id === turnId);
      if (turn) {
        return turn;
      }
    }
    throw new Response("Turn not found", { status: 404 });
  }

  private find(sessionId: string): FixtureSession {
    const session = this.catalogue().find(
      (item) => item.summary.session_id === sessionId,
    );
    if (!session) {
      throw new Response("Session not found", { status: 404 });
    }
    return session;
  }

  private catalogue(): FixtureSession[] {
    return [this.completed(), this.halted(), this.refused()];
  }

  private completed(): FixtureSession {
    const sessionId = FixtureTutorApi.sessionIds.completed;
    const draft =
      "The verb ser agrees with the subject. It is also used for temporary states.";
    const supported = "The verb ser agrees with the subject.";
    const unsupported = "It is also used for temporary states.";
    return {
      summary: this.summary(sessionId, 1, "2026-10-01T09:00:00Z"),
      turns: [
        {
          record_intact: true,
          cited: [
            {
              chunk_id: CHUNK,
              content:
                "Ser agrees with the subject for identity and permanent traits.",
              source: {
                source_uri: "kb://grammar/ser",
                version: "1",
                review_status: "reviewed",
              },
            },
          ],
          record: {
            turn_id: FixtureTutorApi.turnIds.completed,
            session_id: sessionId,
            turn_index: 0,
            learner_prompt: {
              text: "How do I use ser?",
              redacted_categories: [],
            },
            output_before_checks: `${draft} Trust me.`,
            output_after_checks: draft,
            ai_disclosure: DISCLOSURE,
            refused: false,
            safety_flags: [
              {
                category: "register",
                message: "The draft uses a casual register.",
                severity: "medium",
              },
            ],
            source_support: {
              support_ratio: 0.5,
              supported: [
                {
                  text: supported,
                  start: draft.indexOf(supported),
                  end: draft.indexOf(supported) + supported.length,
                  source_ids: [CHUNK],
                },
              ],
              unsupported: [
                {
                  text: unsupported,
                  start: draft.indexOf(unsupported),
                  end: draft.indexOf(unsupported) + unsupported.length,
                  source_ids: [],
                },
              ],
            },
            gate_evaluations: [
              this.passed(
                "context_and_permission",
                "permission.session",
                "The session is open and the requested history fields are allowed.",
              ),
              this.passed(
                "conflict_and_ambiguity",
                "conflict.notes",
                "The retrieved notes agree.",
              ),
              this.passed(
                "sensitivity_and_high_stakes",
                "sensitivity.lesson",
                "The draft stays inside the lesson.",
              ),
              this.passed(
                "drift_and_anomaly",
                "drift.session",
                "The turn stays within the session baseline.",
              ),
            ],
            policy_version: POLICY,
          },
        },
      ],
    };
  }

  private halted(): FixtureSession {
    const sessionId = FixtureTutorApi.sessionIds.halted;
    return {
      summary: this.summary(sessionId, 2, "2026-10-01T10:00:00Z"),
      turns: [
        {
          record_intact: true,
          cited: [
            {
              chunk_id: CHUNK,
              content: "Ser is for identity. Estar is for temporary states.",
              source: {
                source_uri: "kb://grammar/ser-estar",
                version: "2",
                review_status: "reviewed",
              },
            },
          ],
          record: {
            turn_id: FixtureTutorApi.turnIds.halted,
            session_id: sessionId,
            turn_index: 0,
            learner_prompt: {
              text: "Is ser the same as estar?",
              redacted_categories: [],
            },
            output_before_checks: null,
            output_after_checks: null,
            ai_disclosure: null,
            refused: null,
            safety_flags: null,
            source_support: null,
            gate_evaluations: [
              this.passed(
                "context_and_permission",
                "permission.session",
                "The session is open and the requested history fields are allowed.",
              ),
              {
                gate_name: "conflict_and_ambiguity",
                decision: "stop",
                policy_rule_id: "conflict.notes",
                reason: "The retrieved notes disagree about ser and estar.",
              },
              this.notReached("sensitivity_and_high_stakes", "conflict.notes"),
              this.notReached("drift_and_anomaly", "conflict.notes"),
            ],
            policy_version: POLICY,
          },
        },
      ],
    };
  }

  private refused(): FixtureSession {
    const sessionId = FixtureTutorApi.sessionIds.refused;
    return {
      summary: this.summary(sessionId, 3, "2026-10-01T11:00:00Z"),
      turns: [
        {
          record_intact: true,
          cited: [],
          record: {
            turn_id: FixtureTutorApi.turnIds.refused,
            session_id: sessionId,
            turn_index: 0,
            learner_prompt: {
              text: "What is my [address]?",
              redacted_categories: ["address"],
            },
            output_before_checks: null,
            output_after_checks: "This question is outside the lesson.",
            ai_disclosure: DISCLOSURE,
            refused: true,
            safety_flags: [
              {
                category: "out_of_scope",
                message: "The prompt asks for a home address.",
                severity: "high",
              },
            ],
            source_support: null,
            gate_evaluations: [
              this.passed(
                "context_and_permission",
                "permission.session",
                "The session is open and the requested history fields are allowed.",
              ),
              this.passed(
                "conflict_and_ambiguity",
                "conflict.notes",
                "No retrieved notes conflict.",
              ),
              this.passed(
                "sensitivity_and_high_stakes",
                "sensitivity.lesson",
                "The refusal is the safe outcome.",
              ),
              this.passed(
                "drift_and_anomaly",
                "drift.session",
                "The turn stays within the session baseline.",
              ),
            ],
            policy_version: POLICY,
          },
        },
      ],
    };
  }

  private summary(
    sessionId: string,
    learner: number,
    startedAt: string,
  ): SessionSummaryJson {
    return {
      session_id: sessionId,
      learner_id: `10000000-0000-4000-8000-00000000000${learner}`,
      started_at: startedAt,
      stopped_at: null,
      open: true,
    };
  }

  private passed(
    name: GateName,
    rule: string,
    reason: string,
  ): GateEvaluationJson {
    return { gate_name: name, decision: "pass", policy_rule_id: rule, reason };
  }

  private notReached(name: GateName, haltingRule: string): GateEvaluationJson {
    return {
      gate_name: name,
      decision: "not_evaluated",
      policy_rule_id: haltingRule,
      reason: `Not reached because ${haltingRule} stopped the turn.`,
    };
  }
}
