import { describe, expect, it } from "vitest";

import { DraftSegmenter } from "~/.server/draft-segmenter";
import { FixtureTutorApi } from "~/.server/fixture-tutor-api";
import { TurnProjection } from "~/.server/turn-projection";

const projection = new TurnProjection(new DraftSegmenter());
const api = new FixtureTutorApi();

async function project(turnId: string) {
  const detail = await api.turn(turnId);
  return projection.project(detail.record, detail.cited);
}

describe("TurnProjection", () => {
  it("projects a completed turn with disclosure, a flag, and an unsupported span", async () => {
    const turn = await project(FixtureTutorApi.turnIds.completed);
    expect(turn.statusLabel).toBe("Awaiting tutor approval");
    expect(turn.draft?.disclosure).toContain(
      "generated by the tutoring system",
    );
    expect(turn.flags).toHaveLength(1);
    expect(turn.support).toEqual({ ratio: 0.5 });
    expect(turn.context?.[0]).toMatchObject({
      citation: 1,
      reviewStatus: "reviewed",
    });
    expect(turn.draft?.segments).toEqual([
      expect.objectContaining({ kind: "supported", citations: ["1"] }),
      expect.objectContaining({ kind: "plain", text: " " }),
      expect.objectContaining({
        kind: "unsupported",
        text: "It is also used for temporary states.",
      }),
    ]);
    expect(turn.gates.map((gate) => gate.stateText)).toEqual([
      "Checked and passed",
      "Checked and passed",
      "Checked and passed",
      "Checked and passed",
    ]);
  });

  it("projects a halted turn with no draft, no checks, and later gates not reached", async () => {
    const turn = await project(FixtureTutorApi.turnIds.halted);
    expect(turn.statusLabel).toBe("Held for review");
    expect(turn.draft).toBeNull();
    expect(turn.flags).toBeNull();
    expect(turn.support).toBeNull();
    expect(turn.context).toHaveLength(1);
    expect(turn.gates.map((gate) => gate.state)).toEqual([
      "passed",
      "fired",
      "not_reached",
      "not_reached",
    ]);
    expect(turn.gates[1]?.stateText).toBe("Checked and fired (stop)");
  });

  it("projects a refused turn as a refusal, with the redacted category", async () => {
    const turn = await project(FixtureTutorApi.turnIds.refused);
    expect(turn.statusLabel).toBe("Refused");
    expect(turn.draft).toMatchObject({ refused: true, beforeChecks: null });
    expect(turn.draft?.segments).toEqual([
      {
        kind: "plain",
        start: 0,
        text: "This question is outside the lesson.",
      },
    ]);
    expect(turn.prompt.redactedCategories).toEqual(["address"]);
    expect(turn.support).toBeNull();
  });

  it("leaves retrieval unreached and names the halting rule when permission stops the turn", async () => {
    const { record } = await api.turn(FixtureTutorApi.turnIds.halted);
    const turn = projection.project(
      {
        ...record,
        gate_evaluations: [
          {
            gate_name: "context_and_permission",
            decision: "stop",
            reason: "The session is stopped.",
            policy_rule_id: "permission.session",
          },
        ],
      },
      [],
    );
    expect(turn.context).toBeNull();
    expect(turn.gates.slice(1).map((gate) => gate.reason)).toEqual([
      "Not reached because permission.session held the turn.",
      "Not reached because permission.session held the turn.",
      "Not reached because permission.session held the turn.",
    ]);
  });
});
