import { expect, test } from "@playwright/test";

// FixtureTutorApi ids. Duplicated rather than imported: this suite drives the
// app from outside, as a tutor would.
const COMPLETED = "11111111-1111-4111-8111-111111111111";
const HALTED = "22222222-2222-4222-8222-222222222222";
const REFUSED = "33333333-3333-4333-8333-333333333333";

test("a completed turn shows the draft, the disclosure, and an unsupported span", async ({
  page,
}) => {
  const leaked: string[] = [];
  page.on("request", (request) => {
    if (request.url().includes(":8000")) {
      leaked.push(request.url());
    }
  });
  await page.goto("/");
  await page.getByRole("link", { name: `Session ${COMPLETED}` }).click();
  await expect(page.getByText("How do I use ser?")).toBeVisible();
  await expect(page.getByText("Review status reviewed")).toBeVisible();
  await expect(page.getByText("Unsupported", { exact: true })).toBeVisible();
  await expect(
    page.getByText(/generated by the tutoring system/),
  ).toBeVisible();
  await expect(page.getByText("Checked and passed").first()).toBeVisible();
  await expect(page.getByText("Severity medium")).toBeVisible();
  expect(leaked).toEqual([]);
});

test("a halted turn leaves later stages unreached", async ({ page }) => {
  await page.goto(`/sessions/${HALTED}`);
  await expect(
    page.getByText("Held for review", { exact: true }),
  ).toBeVisible();
  await expect(page.getByText("Checked and fired (stop)")).toBeVisible();
  await expect(
    page.getByRole("region", { name: "Generated draft" }),
  ).toContainText("Not reached.");
  await expect(page.getByText("Checks did not run.")).toBeVisible();
});

test("a refused turn is a refusal, and the audit route records the digest", async ({
  page,
}) => {
  await page.goto(`/sessions/${REFUSED}`);
  await expect(page.getByText("Refused", { exact: true })).toBeVisible();
  await expect(
    page.getByText("This question is outside the lesson."),
  ).toBeVisible();
  await expect(page.getByText("address", { exact: true })).toBeVisible();
  await expect(page.getByText("Severity high")).toBeVisible();
  await page.getByRole("link", { name: "Audit record" }).click();
  await expect(
    page.getByRole("heading", { name: "Audit record" }),
  ).toBeVisible();
  await expect(page.getByText("Record digest intact")).toBeVisible();
  await expect(
    page.getByRole("region", { name: "Gate timeline" }),
  ).toBeVisible();
});

test("an id that is not a UUID is a 404, not a backend call", async ({
  page,
}) => {
  const response = await page.goto("/sessions/not-a-session");
  expect(response?.status()).toBe(404);
});
