"""Valid domain objects for model and port tests."""

from datetime import UTC, datetime
from uuid import UUID

from tutor_core.domain.audit.chain import ChainBreak
from tutor_core.domain.models.audit import HumanAction, TurnAuditRecord
from tutor_core.domain.models.learner import (
    HistoryItem,
    LearnerHistorySnapshot,
    LearnerId,
)
from tutor_core.domain.models.retrieval import (
    RetrievalQuery,
    RetrievalResult,
    Snippet,
    SourceRef,
)
from tutor_core.domain.models.safety import (
    ClaimSpan,
    DecodingParams,
    GeneratedUnit,
    GrammarFinding,
    ModelCompletion,
    RedactedText,
    RenderedPrompt,
    SafetyFlag,
    SourceSupportReport,
)
from tutor_core.domain.models.turn import TurnState
from tutor_core.domain.models.verdict import GateVerdict
from tutor_core.domain.policy.policy_card import ArticleMapping, PolicyCard


class Samples:
    """Builders for frozen records and one mutable turn."""

    def when(self) -> datetime:
        return datetime(2026, 9, 21, 12, 0, tzinfo=UTC)

    def learner_id(self) -> LearnerId:
        return LearnerId(value=UUID("00000000-0000-4000-8000-000000000001"))

    def source(self) -> SourceRef:
        return SourceRef(
            document_id=UUID("00000000-0000-4000-8000-000000000002"),
            source_uri="kb://greetings",
            version="1",
            review_status="reviewed",
        )

    def snippet(self) -> Snippet:
        return Snippet(content="Hola means hello.", source=self.source(), ordinal=0)

    def query(self) -> RetrievalQuery:
        return RetrievalQuery(text="how do I greet someone")

    def retrieval(self) -> RetrievalResult:
        return RetrievalResult(
            snippets=(self.snippet(),),
            sources=(self.source(),),
            confidence=0.5,
        )

    def history_item(self) -> HistoryItem:
        return HistoryItem(item_id="greet-1", correct=True, occurred_at=self.when())

    def history(self) -> LearnerHistorySnapshot:
        return LearnerHistorySnapshot(
            learner_id=self.learner_id(),
            proficiency_level="A1",
            events=(self.history_item(),),
        )

    def decoding(self) -> DecodingParams:
        return DecodingParams(temperature=0.0, top_p=1.0, max_tokens=64)

    def safety_flag(self) -> SafetyFlag:
        return SafetyFlag(
            category="proficiency", message="assessed level", severity="low"
        )

    def grammar(self) -> GrammarFinding:
        return GrammarFinding(message="agreement", offset=0, length=2, replacement="is")

    def supported_span(self) -> ClaimSpan:
        return ClaimSpan(
            text="Hola means hello.", start=0, end=17, source_ids=("kb://greetings",)
        )

    def unsupported_span(self) -> ClaimSpan:
        return ClaimSpan(text="invented claim", start=18, end=32)

    def support(self) -> SourceSupportReport:
        return SourceSupportReport(
            supported=(self.supported_span(),),
            unsupported=(self.unsupported_span(),),
            support_ratio=0.5,
        )

    def redacted(self) -> RedactedText:
        return RedactedText(
            text="Where is the library?",
            redacted_categories=(),
            redaction_count=0,
        )

    def rendered_prompt(self) -> RenderedPrompt:
        return RenderedPrompt(text="Explain greetings.", template_version="tpl-1")

    def completion(self) -> ModelCompletion:
        return ModelCompletion(
            text="Hola means hello.",
            model_revision="a" * 40,
            decoding_params=self.decoding(),
        )

    def generated(self) -> GeneratedUnit:
        return GeneratedUnit(
            output_before_checks="Hola means hello.",
            output_after_checks="Hola means hello.",
            ai_disclosure="This reply was generated by an AI tutor.",
            refused=False,
            refusal_reason=None,
            support=self.support(),
            grammar=(self.grammar(),),
        )

    def verdict(self) -> GateVerdict:
        return GateVerdict(
            gate_name="context_and_permission",
            decision="pass",
            reason="in scope",
            policy_rule_id="perm-1",
        )

    def human_action(self) -> HumanAction:
        return HumanAction(
            turn_id=UUID("00000000-0000-4000-8000-000000000003"),
            tutor_id="tutor-1",
            action="approve",
            edited_output=None,
            acted_at=self.when(),
        )

    def chain_break(self) -> ChainBreak:
        return ChainBreak(
            turn_id=UUID("00000000-0000-4000-8000-000000000003"),
            reason="tampered",
        )

    def audit_record(self) -> TurnAuditRecord:
        prompt = "Where is the library?"
        return TurnAuditRecord(
            turn_id=UUID("00000000-0000-4000-8000-000000000003"),
            session_id=UUID("00000000-0000-4000-8000-000000000004"),
            turn_index=0,
            learner_prompt_redacted=prompt,
            redacted_categories=(),
            retrieved_context_ids=(str(self.source().document_id),),
            model_revision="b" * 40,
            template_version="tpl-1",
            decoding_params=self.decoding(),
            output_before_checks="Hola means hello.",
            output_after_checks="Hola means hello.",
            ai_disclosure="This reply was generated by an AI tutor.",
            refused=False,
            safety_flags=(self.safety_flag(),),
            source_support=self.support(),
            policy_version="policy-1",
            previous_record_hash="c" * 64,
            record_hash="d" * 64,
            recorded_at=self.when(),
        )

    def stopped_audit_record(self) -> TurnAuditRecord:
        return TurnAuditRecord(
            turn_id=UUID("00000000-0000-4000-8000-000000000003"),
            session_id=UUID("00000000-0000-4000-8000-000000000004"),
            turn_index=0,
            learner_prompt_redacted="Where is the library?",
            redacted_categories=(),
            retrieved_context_ids=(),
            policy_version="policy-1",
            previous_record_hash="c" * 64,
            record_hash="d" * 64,
            recorded_at=self.when(),
        )

    def article_mapping(self) -> ArticleMapping:
        return ArticleMapping(article="12", locus="per-turn audit log")

    def policy_card(self) -> PolicyCard:
        return PolicyCard(
            version="policy-1",
            allowed_actions=("retrieve_vetted",),
            denied_actions=("open_web",),
            escalation_rules=("pause_routes_to_tutor",),
            article_mappings=(self.article_mapping(),),
        )

    def turn(self) -> TurnState:
        return TurnState(
            turn_id=UUID("00000000-0000-4000-8000-000000000003"),
            session_id=UUID("00000000-0000-4000-8000-000000000004"),
            learner_prompt=self.redacted(),
            retrieved=self.retrieval(),
            generated=self.generated(),
            safety_flags=(self.safety_flag(),),
        )

    def frozen_instances(self) -> tuple[object, ...]:
        return (
            self.query(),
            self.source(),
            self.snippet(),
            self.retrieval(),
            self.learner_id(),
            self.history_item(),
            self.history(),
            self.decoding(),
            self.safety_flag(),
            self.grammar(),
            self.supported_span(),
            self.unsupported_span(),
            self.support(),
            self.redacted(),
            self.rendered_prompt(),
            self.completion(),
            self.generated(),
            self.verdict(),
            self.human_action(),
            self.audit_record(),
            self.chain_break(),
            self.article_mapping(),
            self.policy_card(),
        )
